services:
  - type: web
    name: todo-django
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn todo_project.wsgi:application
    autoDeploy: true
